# UniFi Controller Helm Chart Values

# Persistence Configuration
persistence:
  enabled: true
  storageClass: longhorn
  accessModes: [ReadWriteMany]
  size: 8Gi
  backup:
    enabled: false

# Ingress Configuration
ingress:
  enabled: true
  className: "infra-traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.passthrough: "true"
    external-dns.alpha.kubernetes.io/hostname: unifi.amer.home
    external-dns.alpha.kubernetes.io/ttl: "3600"
    external-dns.alpha.kubernetes.io/manage-record-types: "A"
  hosts:
    - host: unifi.amer.home
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - unifi.amer.home
