apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-groups
data:
  groups.yaml: |
    guests:
      name: Guests
      entities:
        - device_tracker.brayan_iphone
        - device_tracker.eirill_iphone
      all: false
    
