apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-helpers-input-datetime
data:
  bathroom.yaml: |
    # Template for input_datetime helpers per room
    # Usage:
    #   jinja2 input_datetime_template.yaml.j2 -D room=bedroom > input_datetime/bedroom.yaml
    
    # Custom Room Schedule Times (Used when bathroom_custom_schedule is ON)
    bathroom_s1_start:
      name: Bathroom Morning start
      has_time: true
      has_date: false
    
    bathroom_s2_start:
      name: Bathroom Day start
      has_time: true
      has_date: false
    
    bathroom_s3_start:
      name: Bathroom Evening start
      has_time: true
      has_date: false
    
    bathroom_s4_start:
      name: Bathroom Night start
      has_time: true
      has_date: false
  bedroom.yaml: |
    # Template for input_datetime helpers per room
    # Usage:
    #   jinja2 input_datetime_template.yaml.j2 -D room=bedroom > input_datetime/bedroom.yaml
    
    # Custom Room Schedule Times (Used when bedroom_custom_schedule is ON)
    bedroom_s1_start:
      name: Bedroom Morning start
      has_time: true
      has_date: false
    
    bedroom_s2_start:
      name: Bedroom Day start
      has_time: true
      has_date: false
    
    bedroom_s3_start:
      name: Bedroom Evening start
      has_time: true
      has_date: false
    
    bedroom_s4_start:
      name: Bedroom Night start
      has_time: true
      has_date: false
  global_schedule.yaml: |
    global_morning_start:
      name: Global Morning Start
      has_time: true
      has_date: false
      initial: "06:30:00"
    
    global_day_start:
      name: Global Day Start
      has_time: true
      has_date: false
      initial: "10:30:00"
    
    global_evening_start:
      name: Global Evening Start
      has_time: true
      has_date: false
      initial: "18:00:00"
    
    global_night_start:
      name: Global Night Start
      has_time: true
      has_date: false
      initial: "23:00:00"
  hallway.yaml: |
    # Template for input_datetime helpers per room
    # Usage:
    #   jinja2 input_datetime_template.yaml.j2 -D room=bedroom > input_datetime/bedroom.yaml
    
    # Custom Room Schedule Times (Used when hallway_custom_schedule is ON)
    hallway_s1_start:
      name: Hallway Morning start
      has_time: true
      has_date: false
    
    hallway_s2_start:
      name: Hallway Day start
      has_time: true
      has_date: false
    
    hallway_s3_start:
      name: Hallway Evening start
      has_time: true
      has_date: false
    
    hallway_s4_start:
      name: Hallway Night start
      has_time: true
      has_date: false
  kitchen.yaml: |
    # Template for input_datetime helpers per room
    # Usage:
    #   jinja2 input_datetime_template.yaml.j2 -D room=bedroom > input_datetime/bedroom.yaml
    
    # Custom Room Schedule Times (Used when kitchen_custom_schedule is ON)
    kitchen_s1_start:
      name: Kitchen Morning start
      has_time: true
      has_date: false
    
    kitchen_s2_start:
      name: Kitchen Day start
      has_time: true
      has_date: false
    
    kitchen_s3_start:
      name: Kitchen Evening start
      has_time: true
      has_date: false
    
    kitchen_s4_start:
      name: Kitchen Night start
      has_time: true
      has_date: false
  living_room.yaml: |
    # Template for input_datetime helpers per room
    # Usage:
    #   jinja2 input_datetime_template.yaml.j2 -D room=bedroom > input_datetime/bedroom.yaml
    
    # Custom Room Schedule Times (Used when living_room_custom_schedule is ON)
    living_room_s1_start:
      name: Living Room Morning start
      has_time: true
      has_date: false
    
    living_room_s2_start:
      name: Living Room Day start
      has_time: true
      has_date: false
    
    living_room_s3_start:
      name: Living Room Evening start
      has_time: true
      has_date: false
    
    living_room_s4_start:
      name: Living Room Night start
      has_time: true
      has_date: false
